#A YML file is a text document that contains data formatted using YAML (YAML Ain't Markup Language), a human-readable data format used for 
#data serialization. It is used for reading and writing data independent of a specific programming language. Because YAML syntax is language-agnostic, 
#YML files can be incorporated into programs written in most popular programming languages, including C/C++, Ruby, Python, Java, Perl, C#, PHP, and others.

#YML files are most commonly used as configuration files, which define a program or application's settings. If a program uses a YML file as a settings file, 
#you can edit the program's settings by opening and editing the YML file in a text or source code editor. Most settings-related YML files include 
#comments that explain how the file can be used to adjust a program's settings.



version: '3.3'

services:
#'initiate SQL Data Base with all specifications'
  db:
   image: mysql:5.7
   volumes:
   - db_data:/var/lib/mysql
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: somewordpress
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress

#'setup wordpress image with all specifications'
  wordpress:
    depends_on:
    - db
    image: wordpress:php7.4-apache
    ports:
    - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}
